package com.example.demo;


import static org.junit.jupiter.api.Assertions.assertEquals;

// Generated by CodiumAI


import org.junit.platform.commons.annotation.Testable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import com.controller.PlayController;



public class PlayControllerTest {


    // GET request to /play/message returns a ResponseEntity with status code 200 and message "let's play a game!"
    @Testable
    public void test_getGreeting() {
        PlayController playController = new PlayController(null, null, null, null);
        ResponseEntity<String> response = playController.getGreeting();
        assertEquals(HttpStatus.OK, response.getStatusCode());
        assertEquals("let's play a game!", response.getBody());
    }
}
